---
title: "Session 2B"
author: "Alex Vand"
date: "8/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(palmerpenguins)
```

## Plot a function in `ggplot2`

```{r}
# ggplot is expecting a function, not expression

eq <- function(x) {
  
  3 * x ^ 2 + 4
}

# Use stat_function()
# ggplot is expecting a data frame, not vector

ggplot(data = data.frame(x = c(1, 100)), aes(x = x)) +
  stat_function(fun = eq)



```

### Task

Plot $f(x) = 2.4-5x^3+2.1x^2$ over a range from -50 to +50

```{r}
eq2 <- function(x) {
  2.4-5*x^3+2.1*x^2
}

ggplot(data = data.frame(x = c(-50, 50)), aes(x = x)) +
  stat_function(fun = eq2)
```
Alternatively, we can plot this way:
```{r}
ggplot(data = NULL) +
  stat_function(fun = eq2) +
  xlim(min = -50, max = 50)
```

### `penguins` body mass and flipper length

Basic ggplot scatterplot of body mass (y) and flipper length (x)

```{r}
ggplot(data = penguins, aes(x = flipper_length_mm, y = body_mass_g)) +
  geom_point(aes(color = species)) +
  scale_color_manual(values = c("red", "purple", "cyan")) +
  labs(x = "Flipper length (mm)",
       y = "Body mass (g)",
       title = "Palmer penguins size measurements",
       caption = "Data collected by KB Gorman et al. at Palmer Station",
       color = "Species") +
  facet_wrap(~island) +
  theme_minimal()
```

### Higher order derivatives

```{r}
gt <- expression(2.2 + 3.1 * t -5.6 * t ^ 4)

dg_dt <- D(expr = gt, name = "t")

dg_dt
```
```{r}
d2g_dt2 <- D(expr = dg_dt, name = "t")

d2g_dt2
```

## Partial derivatives

```{r}
f_xyz <- expression(2*x*y - 3*x^2*z^3)

df_dx <- D(expr = f_xyz, name = "x")
df_dy <- D(expr = f_xyz, name = "y")
df_dz <- D(expr = f_xyz, name = "z")

df_dx
df_dy
df_dz
```



